# Generated by Django 5.0.14 on 2025-05-24 05:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pedido_producto', '0001_initial'),
        ('repartidor_vehiculo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recorrido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedido_producto.pedido')),
                ('repartidores', models.ManyToManyField(related_name='recorridos', to='repartidor_vehiculo.repartidor')),
            ],
        ),
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=130)),
                ('hora_inicio', models.TimeField()),
                ('duracion', models.DurationField()),
                ('recorrido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actividad_recorrido.recorrido')),
            ],
        ),
    ]
