# Generated by Django 5.0.14 on 2025-05-24 05:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('repartidor_vehiculo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto_Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'Producto o Servicio',
                'verbose_name_plural': 'Productos y Servicios',
                'db_table': 'producto_servicio',
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField()),
                ('direccion_entrega', models.CharField(max_length=255)),
                ('estado', models.CharField(max_length=50)),
                ('cliente', models.ForeignKey(db_column='id_cliente', on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
                ('repartidor', models.ForeignKey(blank=True, db_column='id_repartidor', null=True, on_delete=django.db.models.deletion.SET_NULL, to='repartidor_vehiculo.repartidor')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'db_table': 'pedido',
            },
        ),
        migrations.CreateModel(
            name='Pedido_Producto_Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pedido', models.ForeignKey(db_column='id_pedido', on_delete=django.db.models.deletion.CASCADE, to='pedido_producto.pedido')),
                ('producto_servicio', models.ForeignKey(db_column='id_producto_servicio', on_delete=django.db.models.deletion.CASCADE, to='pedido_producto.producto_servicio')),
            ],
            options={
                'verbose_name': 'Detalle de Pedido',
                'verbose_name_plural': 'Detalles de Pedidos',
                'db_table': 'pedido_producto_servicio',
                'unique_together': {('pedido', 'producto_servicio')},
            },
        ),
    ]
