# Generated by Django 5.0.14 on 2025-06-04 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido_producto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido_producto_servicio',
            name='pedido',
            field=models.ForeignKey(db_column='id_pedido', on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='pedido_producto.pedido'),
        ),
    ]
